version: '3'
services:
  postgres:
    image : postgres:13
    container_name : postgres_db
    environment:
       POSTGRES_USER : postgres
       POSTGRES_PASSWORD : postgres
       POSTGRES_DB : postgres
    ports:
      - "5432:5432"
    volumes: # if i stop my application, my data shouldn't be lost===>store my data
      -  postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

